/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tsdnwdwcwnqygyepojaq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZG53ZHdjd25xeWd5ZXBvamFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTUyMzksImV4cCI6MjA3NDI5MTIzOX0.3MtQ-LHueC_MAy8g9FmzghcKdOHknu-EtRsnbIvdzlQ"